DRIVERS = [
    "Lewis Hamilton",
    "George Russell",
    "Max Verstappen",
    "Sergio Perez",
    "Charles Leclerc",
    "Carlos Sainz",
    "Daniel Ricciardo",
    "Lando Norris",
    "Fernando Alonso",
    "Esteban Ocon",
    "Pierre Gasly",
    "Yuki Tsunoda",
    "Sebastian Vettel",
    "Lance Stroll",
    "Nicholas Latifi",
    "Alex Albon",
    "Valtteri Bottas",
    "Zhou Guanyu",
    "Kevin Magnussen",
    "Mick Schumacher",
]

CONSTRUCTORS = [
    "Mercedes",
    "Red Bull",
    "Ferrari",
    "McLaren",
    "Alpine",
    "AlphaTauri",
    "Aston Martin",
    "Williams",
    "Alfa Romeo",
    "Haas",
]
